### ISSUE TITLE
only works when just the tag file is installed

### ISSUE THREAD

**Issue by scsskid** [Thiousi/kirby-svg-kirbytag#1]
This is great and works great, when you just put the svg.php in default kirby tags folder WITHOUT adding the supplied plugin file

I guess 

    $kirby->set('tag', 'svg', __DIR__ . DS . 'tags');

doesn't work anymore in current release

**Comment by peterstollenwerk** [comment]
To make this work in the plugin structure, you can include the tag-file like this:
```
// kirby-tag.php
$filePath = __DIR__ . DS . 'tags' . DS . 'svg.php';
include( $filePath );

```
